name: flutter_spotify_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  bloc: ^8.1.2
  build_runner: ^2.4.7
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_getit: ^1.2.1
  flutter_localization: any
  flutter_test:
    sdk: flutter
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: any
  intl: ^0.18.0
  provider: ^6.0.5
  replicate: ^1.0.0
  uuid: ^4.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
